version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: /install
      runas: root
    # - location: /start
    #   timeout: 60
    #   runas: root